### ISSUE TITLE
debug overlay not working when using grunt-sass instead of grunt-contrib-sass

### ISSUE THREAD

**Issue by yivi** [ericam/susy#454]
Since libsass apparently still treats `@at root` as a selector; it gets printed in the resulting css. So when using `output: overlay` for the debug grid, we are treated with non-existing grid in exchange for blazing speed. :(

Is there any workaround on the susy side of things, or we have just to wait out until libsass catches up?

**Comment by yivi** [comment]
```
├─┬ grunt-contrib-sass@0.8.1
└─┬ grunt-sass@0.18.1
  ├─┬ node-sass@2.0.1
  │ ├─┬ sass-graph@1.0.3
```
And susy 2.2.2

**Comment by ericam** [comment]
We're waiting for libsass to catch up, but you could certainly build your own workaround. Skip the wrapper mixin, and just call the partial mixins as needed. You can see how it all works here: https://github.com/ericam/susy/blob/master/sass/susy/language/susy/_background.scss#L57

Let me know if you need any help interpreting that. Basically you want all those pieces, pasted at-root instead of calling `@at-root`.

**Comment by docmars** [comment]
I was able to implement this workaround by simply adding:

```sass
head {
  @include overlay-head;
  &:before { @include overlay-trigger; }
  &:hover { @include overlay-trigger-hover; }
}
```

The hover trigger is working just fine. Overlay helps so much when you're already using background images in your layout. :)

**Comment by yivi** [comment]
Simple enough and nicely done. Thanks.

**Comment by sephie** [comment]
It makes the toggle visible, but the overlay setting does not show the columns.
When `output: overlay` is used, should it be toggled on by default?

**Comment by ericam** [comment]
The overlay appears when you hover over the toggle. There is no permanent on or off state - just the hover interaction. Anything else would require JS or extra markup.

**Comment by HugoGiraudel** [comment]
Is this issue still relevant now that LibSass has moved forward?

**Comment by ericam** [comment]
Closing unless there are further updates.
