### ISSUE TITLE
Gallery mixin with hidden elements

### ISSUE THREAD

**Issue by nickbullets** [ericam/susy#458]
Hello!

Here's a codepen for review: http://codepen.io/nickbullets/pen/zxyKwy

Essentially, the problem is even though the `.column_full` has `display: none`, the layout breaks. When the `.column_full` is commented out, the layout works as expected -- to me, anyway.

Presumably, this is because of the gallery mixin's usage of nth-child / type-of but I'm lost as to how to avoid this and also make use of the gallery mixin. I'm not familiar at all with the isolate technique, so maybe this is a side effect as well?

--------------------------

*Side note*: as you can see I need to implement (append) the aforementioned full-width column via JS, so if you're feeling like a superhero, I'm all eyes for any suggestions there Susy-wise and would **GREATLY** appreciate it. Currently, I'm taking the span() approach with clearing both, but the nth-child count is off so the 5th regular-sized column starts too far to the right.

--------------------------

Thank you for your time!
Nik

**Comment by ericam** [comment]
Yeah, this is just a limitation of CSS. You won't be able to do it with `gallery` or anything else counting on `:nth-child`. The best solution is if you can use a simple `span` on all the elements, with gutters `split` or `inside` so that they flow to the next line without needing any modifications on the `last` element.
