### ISSUE TITLE
Whats the equivalent of Bootstrap's offset?

### ISSUE THREAD

**Issue by krzkrzkrz** [ericam/susy#488]
Whats the equivalent of Bootstrap's offset? 

http://getbootstrap.com/css/#grid-offsetting
"Move columns to the right using .col-md-offset-* classes. These classes increase the left margin of a column by * columns. For example, .col-md-offset-4 moves .col-md-4 over four columns."

**Comment by ericam** [comment]
http://susydocs.oddbird.net/en/latest/toolkit/#margins

**Comment by krzkrzkrz** [comment]
Hmmmm, so if I have a div that takes up a span of 10 of 16 and I need this div to start from an offset of 1 column. Should it look like this?

    @include span(10 of 16 last); @include pre(1 of 16);

I've tried this, but not getting what I'm expecting..

**Comment by vjwilson** [comment]
@krzkrzkrz , 

I think what you want is this:

```scss
@include span(10 of 16 at 2);
```

See slide 16 of this presentation [Breaking Free from Bootstrap: Custom Responsive Grids with Sass Susy](http://www.slideshare.net/JamesSteinbach/breaking-free-from-bootstrap)

**Comment by ericam** [comment]
@krzkrzkrz why do you have the `last` keyword on yours? By default, `last` will push your element flush right (actually setting `float: right` on it). You only want `last` when you are covering the final column in your grid, which is not the case here. The way I understand it, you want to fill columns 2-12 of 16 total. Remove `last` and it should work as expected.

@vjwilson Susy has a lot of inter-related settings, which can get complex. The `at 2` location argument only works if you are using `output: isolation` — because otherwise positioning is relative to flow, and Susy doesn't know anything about the DOM.

**Comment by krzkrzkrz** [comment]
Thanks for the feedback! Works!
