### ISSUE TITLE
span with no gutter on right?

### ISSUE THREAD

**Issue by krzkrzkrz** [ericam/susy#502]
I have `@include span(8 of 24);` on three elements. How do I remove all the gutters from the right side?

**Comment by ericam** [comment]
You can use the `no-gutters` keyword to remove gutter-output anywhere you want without changing the grid math: `@include span(8 of 24 no-gutters)`. Or you can set gutters to `0`, if you want the columns to fill in that space: `@include span(8 of 24 0)`. Or, if you really just need to remove the last gutter, you can use `last`: `@include span(last 8 of 24)`.

**Comment by microcipcip** [comment]
@mirisuzanne I have been trying to remove gutters for hours and the only thing that worked was this `span(6 of 12 0)`. Do you know why `span(6 of 12 no-gutters)` doesn't return `25%` but `23.7288%`?

**Comment by mirisuzanne** [comment]
@microcipcip The `no-gutters` keyword is specifically for removing gutter-output *without affecting the math*. If you do what to affect the math, you need to set `('gutters': 0)` (or `of 12 0` in shorthand).

**Comment by microcipcip** [comment]
Ok, I got it, thank you!

**Comment by bradonomics** [comment]
I'm getting compilation errors when using `no-gutters` or `0`: `[susy-parse] Unknown shorthand property: [number] '0'`.

Is this still valid syntax in Susy v3? I can't find anything in the docs.

**Comment by mirisuzanne** [comment]
@bradonomics this issue relates specifically to the mixin output of a gutter on the margin property. Since Susy3 has no mixins, there is no use for this specific syntax.

There is still a syntax for adjusting the internal gutter-size on the fly. See the [Shorthand](http://oddbird.net/susy/docs/api.html) section of the docs, specifically the `set-gutters` keyword. There are also cases where [understanding `spread`](http://oddbird.net/susy/docs/config.html#variable--susy) (how gutters are spanned) will get you farther than changing the gutter sizes themselves.
