### ISSUE TITLE
Discrepancies in Position when Overlay Toggled

### ISSUE THREAD

**Issue by jpgilchrist** [ericam/susy#505]
I have an element that when I hover over the debug/show overlay toggle displays in the exact right position. However, when the toggle is off it seems to be shifted about 2 columns right. Not sure what's going on here. 

```
.fb-button {
    @include container;
    @include span(full);

    background-color: #3a5795;
    border-radius: 4px;
    height: 35px;

    &:before {
      position: absolute;
      width: 35px;
      height: 35px;
      background: url(http://icons.iconarchive.com/icons/danleech/simple/512/facebook-icon.png);
      background-size: 35px 35px;
      background-repeat: no-repeat;
      content: '';
    }

    &:after {
      width: span(2 of 12);
      position: absolute;
      margin-left: span(5 wide of 12);
      height: 35px;
      padding: 8px;
      content: 'Connect with Facebook';
      text-align: center;
    }

    &:hover {
      cursor: pointer;
      background-color: #2c4170;
    }
  }
````

**Comment by ericam** [comment]
The overlay toggle uses generated content on the `:after` pseudo-element. Looks like we're adding `position: relative;` to the container when you hover, and that's changing the context for your absolutely-positioned text.

There's no reason to use the `container` element here. It's meant for handling the very outer (root) wrapper of your entire layout — and should never be used in the same place as a `span`. Even `span(full)` is rarely needed, since block elements span the full width by default.
